name: CI
on:
  push:
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        run: git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
        run: git config user.name "$GITHUB_ACTOR"
        run: npm version minor -m "v%s"
        run: VERSION=$(node -p "require('./package.json').version")
        run: git tag ${VERSION}
        run: git push "https://$GITHUB_ACTOR:${{ secrets.NPM_TOKEN }}@github.com/$GITHUB_REPOSITORY.git" --follow-tags
        run: git push "https://$GITHUB_ACTOR:${{ secrets.NPM_TOKEN }}@github.com/$GITHUB_REPOSITORY.git" --tags
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: Install dependencies
        run: npm install
      - name: Patch Version
        uses: stefanzweifel/git-auto-commit-action@v4
        run: npm run patch:version
      - name: Vscode publish
        uses: JCofman/vscodeaction@master
        with:
          args: publish -p ${{ secrets.VSCE_PAT }} patch
