name: CI
on:
  push:
  pull_request:
    branches: [master]
  workflow_dispatch:

env:
  CURRENT_VERSION: 0
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Update Version
        run: env.CURRENT_VERSION = node -p "require('./package.json').version"
        uses: christian-draeger/increment-semantic-version@1.0.3
        with:
          current-version: $CURRENT_VERSION
          version-fragment: 'bug'
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: Install dependencies
        run: npm install
      - name: Patch Version
        uses: stefanzweifel/git-auto-commit-action@v4
        run: npm run patch:version
      - name: Vscode publish
        uses: JCofman/vscodeaction@master
        with:
          args: publish -p ${{ secrets.VSCE_PAT }} patch
