name: CI
on:
  push:
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: Install dependencies
        run: |
          npm install
          npm install -g vsce
      - name: Vscode publish
        run: |
          vsce publish minor -p ${{ secrets.VSCE_PAT }}
