name: CI
on:
  push:
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: Install dependencies
        run: npm install
      - name: Patch Version
        run: npm run patch:version
      - name: Vscode publish
        uses: JCofman/vscodeaction@master
        with:
          args: publish -p ${{ secrets.VSCE_PAT }}
